spring:
  cloud:
    gateway:
      mvc:
        routes:
        - id: springsecurityjwt
          uri: lb://SPRINGSECURITYJWT
          predicates:
           - Path=/api/v1/auth/**
            
        - id: springauthorservice
          uri: lb://SPRINGAUTHORSERVICE
          predicates:
            - Path=/api/v1/**
            
        - id: springfavoriteservice
          uri: lb://SPRINGFAVORITESERVICE
          predicates:
            - Path=/api/v1/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka